# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-22 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0002_topic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
