# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-22 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0003_topic_fav_nums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorite',
            name='topic',
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='fav_id',
            field=models.IntegerField(default=0, verbose_name='数据id'),
        ),
    ]
