# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-30 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0004_auto_20180422_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='image/default.png', max_length=50, upload_to='', verbose_name='封面图'),
        ),
    ]
